# Generated by Django 4.2.4 on 2024-12-05 09:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ApplicationForm",
        ),
    ]
